-- Fresh baseline for an empty MySQL 8 database.
-- Tables are ordered so every referenced table already exists.

CREATE TABLE `ai_grading_jobs` (
  `max_tokens` int DEFAULT NULL,
  `temperature` decimal(4,2) DEFAULT NULL,
  `active_job_key` bigint DEFAULT NULL,
  `completed_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `failed_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `requested_by` bigint NOT NULL,
  `started_at` datetime(6) DEFAULT NULL,
  `submission_attempt_id` bigint NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `error_message` longtext COLLATE utf8mb4_unicode_ci,
  `model_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `prompt_builder_version` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `prompt_template_version` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `system_prompt` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_prompt` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `model_provider` enum('OPENAI') COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('COMPLETED','FAILED','PENDING','RUNNING') COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_grading_jobs_requested_by` (`requested_by`),
  KEY `idx_ai_grading_jobs_submission_attempt_id` (`submission_attempt_id`),
  CONSTRAINT `fk_ai_grading_jobs_requested_by` FOREIGN KEY (`requested_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_ai_grading_jobs_submission_attempt_id` FOREIGN KEY (`submission_attempt_id`) REFERENCES `submission_attempts` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_grading_results` (
  `ai_score` decimal(8,2) DEFAULT NULL,
  `confidence` decimal(5,4) DEFAULT NULL,
  `max_score` decimal(8,2) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `job_id` bigint NOT NULL,
  `submission_attempt_id` bigint NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `overall_feedback` longtext COLLATE utf8mb4_unicode_ci,
  `raw_response` longtext COLLATE utf8mb4_unicode_ci,
  `summary` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_grading_results_job_id` (`job_id`),
  KEY `idx_ai_grading_results_submission_attempt_id` (`submission_attempt_id`),
  CONSTRAINT `fk_ai_grading_results_submission_attempt_id` FOREIGN KEY (`submission_attempt_id`) REFERENCES `submission_attempts` (`id`),
  CONSTRAINT `fk_ai_grading_results_job_id` FOREIGN KEY (`job_id`) REFERENCES `ai_grading_jobs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_grading_item_results` (
  `ai_score` decimal(8,2) DEFAULT NULL,
  `confidence` decimal(5,4) DEFAULT NULL,
  `max_score` decimal(8,2) DEFAULT NULL,
  `assignment_item_id` bigint NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `result_id` bigint NOT NULL,
  `submission_answer_id` bigint NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `feedback` longtext COLLATE utf8mb4_unicode_ci,
  `rubric_analysis` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `idx_ai_grading_item_results_assignment_item_id` (`assignment_item_id`),
  KEY `idx_ai_grading_item_results_result_id` (`result_id`),
  KEY `idx_ai_grading_item_results_submission_answer_id` (`submission_answer_id`),
  CONSTRAINT `fk_ai_grading_item_results_result_id` FOREIGN KEY (`result_id`) REFERENCES `ai_grading_results` (`id`),
  CONSTRAINT `fk_ai_grading_item_results_submission_answer_id` FOREIGN KEY (`submission_answer_id`) REFERENCES `submission_answers` (`id`),
  CONSTRAINT `fk_ai_grading_item_results_assignment_item_id` FOREIGN KEY (`assignment_item_id`) REFERENCES `assignment_items` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `teacher_reviews` (
  `final_score` decimal(8,2) DEFAULT NULL,
  `max_score` decimal(8,2) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `created_by` bigint NOT NULL,
  `finalized_at` datetime(6) DEFAULT NULL,
  `finalized_by` bigint DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `released_at` datetime(6) DEFAULT NULL,
  `released_by` bigint DEFAULT NULL,
  `selected_ai_grading_result_id` bigint DEFAULT NULL,
  `submission_attempt_id` bigint NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `updated_by` bigint NOT NULL,
  `version` bigint NOT NULL,
  `overall_comment` longtext COLLATE utf8mb4_unicode_ci,
  `status` enum('FINALIZED','IN_PROGRESS','RELEASED') COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_teacher_reviews_submission_attempt_id` (`submission_attempt_id`),
  KEY `idx_teacher_reviews_created_by` (`created_by`),
  KEY `idx_teacher_reviews_finalized_by` (`finalized_by`),
  KEY `idx_teacher_reviews_released_by` (`released_by`),
  KEY `idx_teacher_reviews_selected_ai_grading_result_id` (`selected_ai_grading_result_id`),
  KEY `idx_teacher_reviews_updated_by` (`updated_by`),
  CONSTRAINT `fk_teacher_reviews_selected_ai_grading_result_id` FOREIGN KEY (`selected_ai_grading_result_id`) REFERENCES `ai_grading_results` (`id`),
  CONSTRAINT `fk_teacher_reviews_released_by` FOREIGN KEY (`released_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_teacher_reviews_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_teacher_reviews_finalized_by` FOREIGN KEY (`finalized_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_teacher_reviews_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_teacher_reviews_submission_attempt_id` FOREIGN KEY (`submission_attempt_id`) REFERENCES `submission_attempts` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `teacher_review_items` (
  `display_order_snapshot` int NOT NULL,
  `final_score` decimal(8,2) DEFAULT NULL,
  `max_score` decimal(8,2) NOT NULL,
  `assignment_item_id` bigint NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `review_id` bigint NOT NULL,
  `submission_answer_id` bigint DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `item_comment` longtext COLLATE utf8mb4_unicode_ci,
  `question_title_snapshot` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_teacher_review_items_assignment_item_id` (`assignment_item_id`),
  KEY `idx_teacher_review_items_review_id` (`review_id`),
  KEY `idx_teacher_review_items_submission_answer_id` (`submission_answer_id`),
  CONSTRAINT `fk_teacher_review_items_assignment_item_id` FOREIGN KEY (`assignment_item_id`) REFERENCES `assignment_items` (`id`),
  CONSTRAINT `fk_teacher_review_items_submission_answer_id` FOREIGN KEY (`submission_answer_id`) REFERENCES `submission_answers` (`id`),
  CONSTRAINT `fk_teacher_review_items_review_id` FOREIGN KEY (`review_id`) REFERENCES `teacher_reviews` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
